name: Publish to rubygems

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.10
    - name: Setup Rubygems
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: |
        bash .github/setup-rubygems.sh
    - name: Publish to Rubygems
      run: |
        gem build opsgenie-schedule.gemspec
        gem push "opsgenie-schedule-$(git describe --tags).gem"
